### ISSUE TITLE
REPORTE DE ENTREVISTA_EQUIPO

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/entrevista-equipo-fglr#1]
[REPORTE_ENTREVISTA_EQUIPO-FGLR.pdf](https://github.com/SistemasTecTlaxiaco/entrevista-equipo-fglr/files/7148515/REPORTE_ENTREVISTA_EQUIPO-FGLR.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo. Calificación 20/20.
Evaluado por:
Fernando Miguel López
Luis Carlos Rendón Aparicio
Nayeli Anai González López
Arturo Angón José

**Comment by josealfredo79** [comment]
Bien hecho y revisado.

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
